author: Alex Maimescu
objc: true
umbrella_header: ZappMerchantLib/ZappMerchantLib.h
framework_root: .
sdk: iphonesimulator
copyright: IPCO 2012 Limited
github_url: https://github.com/vocalinkzapp/ZappMerchantLib-R2-iOS
exclude: 
 - ZappMerchantLib/PBBAAnimatable.h
 - ZappMerchantLib/PBBAUIElementAppearance.h